### ISSUE TITLE
Game crash upon start up w/ the mod on

### ISSUE THREAD

**Issue by Mlettuce54** [tvanprooyen/mbm#12] opened 2021-02-26 12:30 UTC
I left a comment about this on the CurseForge page and was told to send the crash log, however, for some reasons it wasn't making any crash log files for it.

The only thing i have to give is the error message given in the launcher upon the crash- however, I don't know if this is just a generic crash message or not. Alas, it's all I have.

Thank you in advance.

![image](https://user-images.githubusercontent.com/79701269/109300380-56802700-782e-11eb-9401-4931c1e49cb4.png)

**Comment by tvanprooyen** [comment] 2021-03-03 07:23
Thank you for posting this to this. Unfortunately, this isn't much to go on... Lots of things could potentially cause an exit code 0. How many mods do you have installed? if you could send me a list. I will try to replicate the results and let you know what I find.

**Comment by linklover26** [comment] 2021-03-18 21:40
This happened to me too. I am testing all my mods as we speak. I will come back with my findings

**Comment by linklover26** [comment] 2021-03-18 22:07
After 19 test, if Origins Classes seems to mess up things. I will leave this form since your mod works fine for me. I will be moving this to Origins Classes. I wish you a great day!

**Comment by tvanprooyen** [comment] 2021-03-19 19:07
You too, thanks!

**Closed** 2021-04-27 09:20 UTC

**Comment by tvanprooyen** [comment] 2021-05-26 23:45
This has been an Identified issue. The cause is by both mods interfacing with AxeItem. In this case, the issue is caused my mbm taking over the class rather than injecting the code . The iissue will be updated/tracked here: https://github.com/tvanprooyen/mbm/issues/18

**Comment by tvanprooyen** [comment] 2021-06-01 09:24
Updated AxeItemMixin to work with origins. Tested it compatibility and origins now loads with MBM.
